src/java/bean/Status.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bean;

/**
 *
 * @author Marcus
 */
public class Status {
    private int StatusID;
    private String StatusName;

    public int getStatusID() {
        return StatusID;
    }

    public void setStatusID(int StatusID) {
        this.StatusID = StatusID;
    }

    public String getStatusName() {
        return StatusName;
    }

    public void setStatusName(String StatusName) {
        this.StatusName = StatusName;
    }
    
    @Override
    public String toString(){
        return this.StatusName;
    }
    
}

src/java/pageController/bo_editStaffController.java
package pageController;

import beanController.DepartmentController;
import beanController.LoginStaffController;
import beanController.StaffController;
import beanController.UserRoleController;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


public class bo_editStaffController extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setAttribute("CurrentStaff", new LoginStaffController().getStaff(Integer.parseInt(request.getParameter("staffid"))));
        request.setAttribute("userrole", new UserRoleController().getRoleList());
        request.setAttribute("departments", new DepartmentController().getDeptList());
        RequestDispatcher rd = request.getRequestDispatcher("/WEB-INF/bo/bo_editstaff.jsp");
        rd.forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        new LoginStaffController().updateStaffByMap(request.getParameterMap());
        response.sendRedirect("bo_editStaff?staffid="+request.getParameter("staffid"));
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/pageController/bo_taskQueryController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pageController;

import bean.Priority;
import bean.Status;
import bean.Task;
import bean.TaskType;
import beanController.PriorityController;
import beanController.StatusController;
import beanController.TaskListController;
import beanController.TaskTypeController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
/**
 *
 * @author Joseph
 */
public class bo_taskQueryController extends pageController {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        RequestDispatcher dispatcher;
        ArrayList<TaskType> types = new TaskTypeController().getTypeList();
        ArrayList<Priority> priority = new PriorityController().getPriorityList();
        ArrayList<Status> status = new StatusController().getStatusList();
        try {
            request.setAttribute("tasktype", types);
            request.setAttribute("taskpriority", priority);
            request.setAttribute("taskstatus", status);
            bo_redirectWithAuth(request.getSession(false), response);
            dispatcher = request.getRequestDispatcher("/WEB-INF/bo/bo_taskquery.jsp");
            dispatcher.forward(request, response);
        } catch (Exception e) {
        }
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        Map<String, String[]> pMap = request.getParameterMap();
        TaskListController tlc = new TaskListController();
        ArrayList<Task> tasks = tlc.getTasksByMap(pMap);
        doGet(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

web/WEB-INF/bo/bo_createstaff.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Create Staff</title>
        <%@include file="../style_jsp/default_header_style.jsp" %>
        <link href="css/pnotify.custom.min.css" rel="stylesheet" type="text/css"/>
        <script src="js/pnotify.custom.min.js"></script>
        <style>
            label{
                color: #666666;
                font-weight: normal;
                font-style: italic;
            }
        </style>
        <script>
            $(document).ready(displayMessage);
            function displayMessage() {
                var create_success = "${requestScope.create_success}";
                if (create_success == "true")
                    new PNotify({
                        title: 'Staff Created Successfully',
                        text: '',
                        type: 'success'
                    });
                else if (create_success == "false") {
                    new PNotify({
                        title: "Staff can't be created",
                        text: 'Something went wrong',
                        type: 'error'
                    });
                }
            }
        </script>
    </head>
    <body>
        <jsp:include page="../template_jsp/bo_header.jsp" flush="true" />
        <div class="container">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6 staff-detail-container">
                    <h3 class="txt-center MB20">Create Staff</h3>
                    <form class="form-horizontal" role="form" action="bo_createStaff" method="POST" onsubmit="hashPW()">
                        <div class="form-group">
                            <label for="username" class="col-sm-3 col-md-3 control-label">User Name</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="text" class="form-control" name="username" required/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="realname" class="col-sm-3 col-md-3 control-label">Real Name</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="text" class="form-control" name="realname" required/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="role" class="col-sm-3 col-md-3 control-label">Role</label>
                            <div class="col-sm-9 col-md-9">
                                <select name="role" class="form-control">
                                    <c:forEach items="${requestScope.userrole}" var="role">
                                        <option value="${role.roleID}">${role}</option>
                                    </c:forEach>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="department" class="col-sm-3 col-md-3 control-label">Department</label>
                            <div class="col-sm-9 col-md-9">
                                <select name="department" class="form-control">
                                    <c:forEach items="${requestScope.departments}" var="dept">
                                        <option value="${dept.deptID}">${dept}</option>
                                    </c:forEach>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-sm-3 col-md-3 control-label">Email</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="email" class="form-control" name="email" required/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="telno" class="col-sm-3 col-md-3 control-label">Tel No.</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="telno" required/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 col-md-3 control-label"></label>
                            <div class="col-sm-9 col-md-9">
                                <input type="submit" class="btn btn-primary" value="Submit"/>
                                <input type="reset" class="btn btn-danger" value="Reset"/>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
        <%@include file="../template_jsp/footer-dark.jsp" %>
    </body>
</html>

web/WEB-INF/bo/bo_editstaff.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<jsp:useBean id="CurrentStaff" class="bean.LoginStaff" scope="request" />
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Edit staff - ${CurrentStaff.userName}</title>
        <%@include file="../style_jsp/default_style.jsp" %>
        <script src="js/md5.js"></script>
        <link rel="stylesheet" href="css/user.css" />
        <style>
            label{
                color: #666666;
                font-weight: normal;
                font-style: italic;
            }

            .container{
                margin-top: 30px;
            }
        </style>
        <script>
            function hashPW() {
                if ($('input[name="pwd"]').val().length !== 0) {
                    var hash = CryptoJS.MD5($('input[name="pwd"]').val());
                    $('input[name="pwd"]').val(hash);
                } else {
                    $('input[name="pwd"]').val("");
                }
            }
        </script>
    </head>
    <body>
        <div class="container">
            <div class="row txt-center">
                <img class="img-circle" style="width: 150px; border: 4px #F5F5F5 solid;" id="staff_photo" src="img/staffphoto/${CurrentStaff.staffID}.jpg" onerror="this.src='img/staffphoto/default.jpg'" />
            </div>
            <form class="form-horizontal MT15" role="form" action="bo_editStaff" method="POST" onsubmit="hashPW()">
                <div class="form-group">
                    <label for="staffid" class="col-sm-3 col-md-3 control-label">Staff ID</label>
                    <div class="col-sm-9 col-md-9">
                        <input type="text" class="form-control" name="staffid" readonly required value="${CurrentStaff.staffID}"/>
                    </div>
                </div> 
                <div class="form-group">
                    <label for="username" class="col-sm-3 col-md-3 control-label">User Name</label>
                    <div class="col-sm-9 col-md-9">
                        <input type="text" class="form-control" name="username" readonly required value="${CurrentStaff.userName}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="realname" class="col-sm-3 col-md-3 control-label">Real Name</label>
                    <div class="col-sm-9 col-md-9">
                        <input type="text" class="form-control" name="realname" required value="${CurrentStaff.realName}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="pwd" class="col-sm-3 col-md-3 control-label">Password</label>
                    <div class="col-sm-9 col-md-9">
                        <input type="password" class="form-control" name="pwd" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="roleid" class="col-sm-3 col-md-3 control-label">Role</label>
                    <div class="col-sm-9 col-md-9">
                        <select name="roleid" class="form-control">
                            <option value="">All</option>
                            <c:forEach items="${requestScope.userrole}" var="role">   
                                <option value="${role.roleID}" <c:if test="${CurrentStaff.role.roleID == role.roleID}"><c:out value="selected" /></c:if>>
                                    ${role}
                                </option>
                            </c:forEach>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="deptid" class="col-sm-3 col-md-3 control-label">Department</label>
                    <div class="col-sm-9 col-md-9">
                        <select name="deptid" class="form-control">
                            <option value="">All</option>
                            <c:forEach items="${requestScope.departments}" var="dept">
                                <option value="${dept.deptID}" <c:if test="${CurrentStaff.dept.deptID == dept.deptID}"><c:out value="selected" /></c:if>>
                                    ${dept}
                                </option>
                            </c:forEach>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-sm-3 col-md-3 control-label">Email</label>
                    <div class="col-sm-9 col-md-9">
                        <input type="email" class="form-control" name="email" value="${CurrentStaff.eMail}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="contactnumber" class="col-sm-3 col-md-3 control-label">Tel No.</label>
                    <div class="col-sm-9 col-md-9">
                        <input type="number" class="form-control" name="contactnumber" value="${CurrentStaff.tel}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 col-md-3 control-label"></label>
                    <div class="col-sm-9 col-md-9">
                        <input type="submit" class="btn btn-primary" value="Submit"/>
                    </div>
                </div>
            </form>
        </div>
    </body>
</html>

web/WEB-INF/bo/bo_index.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <%@include file="../style_jsp/default_header_style.jsp" %>
        <script src="js/md5.js"></script>
        <style>
            /*Custom style of this webpage*/
            .form-signin{
                max-width: 350px;
            }

            input[type="text"]{
                border-radius: 5px 5px 0px 0px;
            }

            input[type="password"]{
                border-radius: 0px 0px 5px 5px;
                margin-top: 0px;
            }

            input[type="submit"]{
                margin-top: 10px;
            }
        </style>
        <script>
            $(document).ready(function(){
                if (<%=request.getAttribute("invalid_login")%>) {
                    var l = 20;
                    for (var i = 0; i < 10; i++)
                        $("#login-form").animate({'margin-left': "+=" + (l = -l) + 'px'}, 50);
                }
            });
            
            function hashPW() {
                var hash = CryptoJS.MD5($('input[name="password"]').val());
                $('input[name="password"]').val(hash);
            }
        </script>
        <title>BackOffice - index</title>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="index">Unnamed system</a>
                </div>
            </div><!--/.nav-collapse -->
        </div>
        <div class="container">
            <form class="form-signin div-center" id="login-form" role="form" action="bo_index" method="POST" onsubmit="hashPW()">
                <h4 class="form-signin-heading">Please sign in</h4>
                <input type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="">
                <input type="password" class="form-control" name="password" placeholder="Password" required>
                <input class="btn btn-lg btn-primary btn-block" type="submit" value="Log In" />
            </form>
        </div>
        <%@include file="../template_jsp/footer-dark.jsp" %>
    </body>
</html>

web/WEB-INF/bo/bo_logquery.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Log Query</title>
        <%@include file="../style_jsp/default_header_style.jsp" %>
        <style>
            label{
                color: #666666;
                font-weight: normal;
                font-style: italic;
            }
            .filter_block{
                background-color: #F5F5F5;
                border-radius: 5px;
            }

            td{
                vertical-align: middle !important;
            }
            
            .result_block{
                border: none;
                width: 100%;
                min-height: 100%;
            }
        </style>
        <script>
            function changeURL(){
               var url = $(".result_block").data("url")+"?";
               $(".form-horizontal .col-md-6 input").each(function(){
                  url += $(this).attr("name") + "=" + $(this).val() + "&"; 
               });
               $(".form-horizontal .col-md-6 select").each(function(){
                  url += $(this).attr("name") + "=" + $(this).val() + "&"; 
               });
               $(".result_block").attr("src", url);
               return false
            }
        </script>
    </head>
    <body>
        <jsp:include page="../template_jsp/bo_header.jsp" flush="true" />
        <div class="container">
            <div class="filter_block MB20 PT20 row">
                <form class="form-horizontal" role="form" onsubmit="return changeURL()">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="logid" class="col-sm-3 col-md-3 control-label">Log ID</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="logid"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="logtype" class="col-sm-3 col-md-3 control-label">Log Type</label>
                            <div class="col-sm-9 col-md-9">
                                <select name="logtype" class="form-control">
                                    <option value="" selected>all</option>
                                    <c:forEach items="${requestScope.logtypelist}" var="logtype">
                                    <option value="${logtype}">${logtype}</option>
                                    </c:forEach>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="taskid" class="col-sm-3 col-md-3 control-label">Task ID</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="taskid"/>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="assigneeid" class="col-sm-3 col-md-3 control-label">Assignee ID</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="assigneeid"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="reporterid" class="col-sm-3 col-md-3 control-label">Reporter ID</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="reporterid"/>
                            </div>
                        </div>       
                    </div>
                    <div class="col-sm-12 col-md-12 MT20 txt-center">
                        <div class="form-group row">
                            <input type="submit" class="btn btn-primary" value="Submit"/>
                            <input type="reset" class="btn btn-danger" value="Reset"/>
                        </div>
                    </div>
                </form>
            </div>
            <iframe class="result_block" src="" data-url="bo_logQueryResult">
            </iframe>
        </div>
        <%@include file="../template_jsp/footer-dark.jsp" %>
    </body>
</html>

web/WEB-INF/bo/bo_logquery_result.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="../style_jsp/default_style.jsp" %>
    </head>
    <body>
        <div class="result_block">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Log ID</th>
                        <th>Log Type</th>
                        <th>Task ID</th>
                        <th>Assignee</th>
                        <th>Reporter</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    <c:forEach items="${requestScope.result}" var="log">
                        <tr>
                            <td>${log.logID}</td>
                            <td>${log.logType}</td>
                            <td onclick="window.open('taskdetail?taskid=${log.task.taskID}')" style="cursor: pointer">${log.task.taskID}</td>
                            <td>${log.assignee}  (${log.assignee.staffID})</td>
                            <td>${log.reporter}  (${log.reporter.staffID})</td>
                            <td>${log.date}</td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>
        </div>
    </body>
</html>

web/WEB-INF/bo/bo_taskquery.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Task Query</title>
        <%@include file="../style_jsp/default_header_style.jsp" %>
        <style>
            label{
                color: #666666;
                font-weight: normal;
                font-style: italic;
            }
            .filter_block{
                background-color: #F5F5F5;
                border-radius: 5px;
            }
            .result_block{
                border: none;
                width: 100%;
                min-height: 100%;
            }
        </style>
        <script>
            function changeURL(){
               var url = $(".result_block").data("url")+"?";
               $(".form-horizontal .col-md-6 input").each(function(){
                  url += $(this).attr("name") + "=" + $(this).val() + "&"; 
               });
               $(".form-horizontal .col-md-6 select").each(function(){
                  url += $(this).attr("name") + "=" + $(this).val() + "&"; 
               });
               $(".result_block").attr("src", url);
               return false
            }
        </script>
    </head>
    <body>
        <jsp:include page="../template_jsp/bo_header.jsp" flush="true" />
        <div class="container">
            <div class="filter_block MB20 PT20 row">
                <form class="form-horizontal" role="form" onsubmit="return changeURL()">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="taskid" class="col-sm-3 col-md-3 control-label">Task ID</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="taskid" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="taskname" class="col-sm-3 col-md-3 control-label">Task Title</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="text" class="form-control" name="taskname" />
                            </div>
                        </div> 
                        <div class="form-group">
                            <label for="typeid" class="col-sm-3 col-md-3 control-label">Task Type</label>
                            <div class="col-sm-9 col-md-9">
                                <select name="typeid" class="form-control">
                                    <option value="" selected>All</option>
                                    <c:forEach items="${requestScope.tasktype}" var="type">
                                    <option value="${type.typeID}">${type}</option>
                                    </c:forEach>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="priority" class="col-sm-3 col-md-3 control-label">Task Priority</label>
                            <div class="col-sm-9 col-md-9">
                                <select name="priorityid" class="form-control">
                                    <option value="" selected>All</option>
                                    <c:forEach items="${requestScope.taskpriority}" var="priority">
                                    <option value="${priority.priorityID}">${priority}</option>
                                    </c:forEach>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="status" class="col-sm-3 col-md-3 control-label">Task Status</label>
                            <div class="col-sm-9 col-md-9">
                                <select name="statusid" class="form-control">
                                    <option value="" selected>All</option>
                                    <c:forEach items="${requestScope.taskstatus}" var="status">
                                    <option value="${status.statusID}">${status}</option>
                                    </c:forEach>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="assigneeid" class="col-sm-3 col-md-3 control-label">Assignee ID</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="assigneeid" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="reporterid" class="col-sm-3 col-md-3 control-label">Reporter ID</label>
                            <div class="col-sm-9 col-md-9">
                                <input type="number" class="form-control" name="reporterid" />
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12 MT20 txt-center">
                        <div class="form-group row">
                            <input type="submit" class="btn btn-primary" value="Submit">
                            <input type="reset" class="btn btn-danger" value="Reset">
                        </div>
                    </div>
                </form>
            </div>
            <iframe class="result_block" src="" data-url="bo_taskQueryResult">
            </iframe>
        </div>
        <%@include file="../template_jsp/footer-dark.jsp" %>
    </body>
</html>